spring:
  datasource:
    name: ecommerce
    url: jdbc:h2:mem:ecommerce;TRACE_LEVEL_FILE=4;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
